BookParkingSlot/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('parking-lot/',include('parking_lot.urls', namespace='parking_lot')),
    path('employees/',include('employees.urls')),
    path('api/',include('parking_lot.api.urls')),
]

employees/urls.py
from django.urls import path

from . import views

app_name = 'employees'

urlpatterns = [
    path('register/',
         views.EmployeeRegistrationView.as_view(),
         name='employee_registration'),
    path('login/',
         views.EmployeeLoginView.as_view(),
         name='employee_login'),
    path('logout/',
         views.EmployeeLogoutView.as_view(),
         name='employee_logout'),
]

parking_lot/api/urls.py
from django.urls import path
from . import views as api_views

app_name = 'parking_lot'

urlpatterns = [
    path('list/',api_views.ParkingSlotListView.as_view()),
    path('detail/<int:slot_number>',api_views.ParkingSlotDetailView.as_view()),
]

parking_lot/urls.py
from django.urls import path,include
from . import views

app_name = 'parking_lot'

urlpatterns = [
    path('list/',
         views.parking_slot_list,
         name='parking_slot_list'),
    path('detail/<int:id>/',
         views.parking_slot_detail,
         name='parking_slot_detail'),
    path('create/',
         views.CreateParkingSlotView.as_view(),
         name='parking_slot_create'),
    path('<int:slot_number>/edit',
         views.EditParkingSlotView.as_view(),
         name='parking_slot_edit'),
    path('<int:slot_number>/delete',
         views.DeleteParkingSlotView.as_view(),
         name='parking_slot_delete'),
    path('<int:slot_number>/reservation/create',
         views.CreateReservationView.as_view(),
         name='reservation_create'),
    path('<int:slot_number>/reservation/<int:pk>/edit',
         views.EditReservationView.as_view(),
         name='reservation_edit'),
    path('<int:slot_number>/reservation/<int:pk>/delete',
         views.DeleteReservationView.as_view(),
         name='reservation_delete'),
]

parking_lot/models.py
from django.db import models
from django.urls import reverse
from employees.models import Employee
from django.db.models import F,Q
import datetime


class ParkingSlot(models.Model):
    slot_number = models.PositiveIntegerField()

    def __str__(self):
        return f'Parking Slot No. {self.slot_number}'

    def get_absolute_url(self):
        return reverse('parking_lot:parking_slot_detail',
                       args=[self.slot_number])



class Reservation(models.Model):
    slot = models.ForeignKey(ParkingSlot,
                                     related_name='reservations',
                                     on_delete=models.CASCADE)
    booked_by = models.OneToOneField(Employee,
                                     related_name='booked_parking_slot',
                                     on_delete=models.CASCADE)
    booked_from = models.DateTimeField()
    booked_until = models.DateTimeField()

    @property
    def expiration(self):
        if self.booked_until > self.booked_until.today():
            return True
        return False

    def __str__(self):
        return f'Booked from {self.booked_from} || until {self.booked_until} || by {self.booked_by.user.username}'

    @staticmethod
    def get_previous_daytime():
        now = datetime.datetime.now()
        prev_date = now - datetime.timedelta(1)
        prev_time = now.time().max
        prev_datetime = datetime.datetime.combine(prev_date, prev_time)
        return prev_datetime

    class Meta:
        constraints = [
            models.CheckConstraint(
                name='start_date_before_end_date',
                check=Q(booked_from__lt=F("booked_until"))
            )
        ]

parking_lot/api/views.py
from rest_framework.views import APIView
from rest_framework import generics
from rest_framework.response import Response

from ..models import ParkingSlot
from .serializers import ParkingSlotSerializer, ReservationSerializer

class ParkingSlotListView(generics.ListAPIView):
    queryset = ParkingSlot.objects.all()
    serializer_class = ParkingSlotSerializer

class ParkingSlotDetailView(APIView):
    serializer_class = ParkingSlotSerializer
    def get(self,request,slot_number):
        slot = ParkingSlot.objects.get(slot_number=slot_number)
        result = ParkingSlotSerializer(slot).data
        result['reservations'] = []
        for reservation in slot.reservations.all():
            reservation_dict = ReservationSerializer(reservation).data
            result['reservations'].append(reservation_dict)

        return Response(result)

parking_lot/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

from .models import ParkingSlot,Reservation
#from .forms import ReservationCreateForm

import datetime
from .services import to_datetime

"""Views for list and detail parking slots"""

def parking_slot_detail(request,id):
    slot = get_object_or_404(ParkingSlot,slot_number=id)

    return render(request,
                  'slot_detail.html',
                  {'slot':slot})


def parking_slot_list(request):
    parking_slot_list = ParkingSlot.objects.all()
    day = datetime.date.today()

    context = {"parking_slot_list":parking_slot_list,
                   "day":day}

    response = render(request,
                      'slot_list.html',
                      context=context)

    if request.method == 'POST':
        if request.POST['day'] != "":
            day = request.POST['day']
            new_day = datetime.datetime.strptime(day,"%Y-%m-%d")
            context.update({"day":new_day})
            return render(request,
                          'slot_list.html',
                          context=context)
        else:
            return response

    return response

"""Views for creating/updating/deleting parking slots"""

class ChangeParkingSlotMixin(PermissionRequiredMixin):
    model = ParkingSlot
    fields = ['slot_number']
    success_url = reverse_lazy('parking_lot:parking_slot_list')
    template_name = 'slot_form.html'

class CreateParkingSlotView(ChangeParkingSlotMixin,generic.CreateView):
    permission_required = 'parking_lot.add_parkingslot'

class EditParkingSlotView(ChangeParkingSlotMixin, generic.UpdateView):
    permission_required = 'parking_lot.change_parkingslot'

    def get_object(self, queryset=None):
        obj = ParkingSlot.objects.get(slot_number=self.kwargs['slot_number'])
        return obj

class DeleteParkingSlotView(PermissionRequiredMixin,generic.DeleteView):
    model = ParkingSlot
    success_url = reverse_lazy('parking_lot:parking_slot_list')
    template_name = 'slot_delete_confirm.html'
    permission_required = 'parking_lot.delete_parkingslot'


    def get_object(self, queryset=None):
        obj = ParkingSlot.objects.get(slot_number=self.kwargs['slot_number'])
        return obj

"""Views for creating/updating/deleting reservations"""

class ReservationMixinView(LoginRequiredMixin,generic.FormView):
    model = Reservation
    success_url = reverse_lazy('parking_lot:parking_slot_list')
    template_name = 'reservation/reservation_form.html'
    fields = ['booked_from','booked_until']

    def get_queryset(self):
        slot_resns = Reservation.objects.filter(slot__slot_number=self.kwargs['slot_number'])
        return slot_resns

    def post(self, request, *args, **kwargs):
        booked_from_this = to_datetime(request.POST['booked_from'])
        booked_until_this = to_datetime(request.POST['booked_until'])
        slot_reservations = self.get_queryset()
        is_valid = False
        if slot_reservations.exists():
            for r in slot_reservations:
                if r.booked_by.user != request.user:
                    if (booked_from_this < r.booked_from.timestamp()) \
                            and (booked_until_this < r.booked_from.timestamp()):
                        is_valid = True
                    elif booked_from_this > r.booked_until.timestamp():
                        is_valid = True
                    else:
                        is_valid = False
                        break
                else:
                     is_valid = True
          else:
            is_valid = True

        if is_valid:
            return self.form_valid(self.get_form())
        else:
            raise ValidationError('Dont interrupt others reservation')


class CreateReservationView(ReservationMixinView,LoginRequiredMixin, generic.CreateView):
    def get_object(self, queryset=None):
        object = ParkingSlot.objects.get(slot_number=self.kwargs['slot_number'])
        return object

    def form_valid(self, form):
        form.instance.booked_by = self.request.user.employee
        form.instance.slot = self.get_object()
        return super().form_valid(form)


class EditReservationView(ReservationMixinView,LoginRequiredMixin, generic.UpdateView):
    def form_valid(self, form):
        form.instance.id = self.kwargs['pk']
        form.instance.booked_by = self.request.user.employee
        form.instance.slot = ParkingSlot.objects.get(slot_number=self.kwargs['slot_number'])
        form.instance.booked_from = self.request.POST['booked_from']
        form.instance.booked_until = self.request.POST['booked_until']
        return super().form_valid(form)


class DeleteReservationView(LoginRequiredMixin, generic.DeleteView):
    model = Reservation
    success_url = reverse_lazy('parking_lot:parking_slot_list')
    template_name = 'reservation/reservation_delete_confirm.html'

parking_lot/templates/slot_delete_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete slot {{ object }}</title>
</head>
<body>
    <h1>Delete {{ object }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}</p>
        <input type="submit" value="Confirm">
    </form>

</body>
</html>

parking_lot/templates/slot_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ slot }} detail</title>
</head>
<body>
<h3>
    {% if request.user.is_authenticated %}
        Hello {{ request.user.username }}
        <p><a href="{% url "employees:employee_logout" %}">Log-out</a></p>
    {% else %}
        <p><a href="{% url "employees:employee_registration" %}">Sign Up</a></p>
        <p><a href="{% url "employees:employee_login" %}">Log-in</a></p>
    {% endif %}
</h3>
<h1>{{ slot }} detail</h1>
<h4>
    {% if request.user.employee.booked_parking_slot%}

    {% else %}
        <a href="{% url "parking_lot:reservation_create" slot.slot_number %}">Create reservation</a>
    {% endif %}
</h4>
<h2>Reservations:</h2>
<ul>
    {% for r in slot.reservations.all %}
       <li>Reservation by {{ r.booked_by.user.username }} on {{ r.booked_from }}
           until {{ r.booked_until }}</li>
        {% if r.booked_by.user == request.user %}
            <a href="{% url "parking_lot:reservation_edit" slot_number=slot.slot_number pk=r.id %}">Edit</a>
            <a href="{% url "parking_lot:reservation_delete" slot_number=slot.slot_number pk=r.id%}">Delete</a>
        {% endif %}
    {% empty %}
        No reservations yet.
    {% endfor %}
</ul>

</body>
</html>

parking_lot/templates/slot_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if object %}
            Edit Slot {{ object }}
            {% else %}
            Create a Slot
        {% endif %}
    </title>
</head>
<body>
    <h1>
        {% if object %}
            Edit Slot {{ object }}
        {% else %}
            Create a Slot
        {% endif %}
    </h1>

    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Save slot"></p>
    </form>
</body>
</html>

parking_lot/templates/slot_list.html
{% load parking_lot_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parking Slots List</title>
</head>
<body>
<h3>
    {% if request.user.is_authenticated %}
        Hello {{ request.user.username }}
        <p><a href="{% url "employees:employee_logout" %}">Log-out</a></p>
    {% else %}
        <p><a href="{% url "employees:employee_registration" %}">Sign Up</a></p>
        <p><a href="{% url "employees:employee_login" %}">Log-in</a></p>
    {% endif %}
</h3>


<h1>Parking slots list</h1>

<h2>Slots for {{ day }}</h2>

<h4>
    <form action="." method="get">
        <label for="day">Set up the date</label>
        {% csrf_token %}
        <input type="date" id="day" name="day" value="{{ day }}">
        <input type="submit" formmethod="post" value="Set">
    </form>
</h4>

{% if request.user.employee.role == 'manager' %}
    <a href="{% url "parking_lot:parking_slot_create" %}">Create slot</a>
{% endif %}
<ul>
    {% for slot in parking_slot_list %}
        <input type="hidden" name="slot_number" value="{{ slot.slot_number }}">
        <li>
            <h3>
                <p><a href="{{ slot.get_absolute_url }}">{{ slot }}</a>
                    {% if request.user.employee.role == 'manager' %}
                        ||<a href="{% url "parking_lot:parking_slot_delete" slot.slot_number%}">delete</a>||
                        <a href="{% url "parking_lot:parking_slot_edit" slot.slot_number%}">edit</a>
                        </p>

                    {% endif %}
            </h3>
        </li>

        <h4>Reservations:</h4>
        <ul>
            {% for r in slot.reservations|day_filter:day %}
                <li>
                    { from: {{ r.booked_from }} |
                    until: {{ r.booked_until }} |
                    by: {{ r.booked_by.user.username }} }
                </li>
                {% empty %}
                    No reservations yet.
            {% endfor %}
        </ul>
    {% endfor %}
</ul>
</body>
</html>